### ISSUE TITLE
[question] How to use this with webpack?

### ISSUE THREAD

**Issue by kittaakos** [bnielsen1965/wska#1]
I have tried several webpack configurations to get this running in the browser. Is that possible at all?

I have tried it with the following four configurations:

```
node: {
  crypto: true
}
```

```
node: {
  crypto: 'empty'
}
```

```
external: {
  'crypto': 'window.crypto'
}
```

```
external: {
  'crypto': 'crypto'
}
```

With the first three, I had the following error:
```
Error: TypeError: crypto.randomBytes is not a function
    at createWebSocket (index.js:45)
    at new WebSocketKeepAlive (index.js:37)
    at WebSocketConnectionProvider.createWebSocket (connection.ts:72)
    at WebSocketConnectionProvider.listen (connection.ts:42)
    at WebSocketConnectionProvider.createProxy (connection.ts:30)
    at Binding.dynamicValue (logger-frontend-module.ts:27)
    at resolver.js:63
    at invokeFactory (resolver.js:10)
    at resolver.js:63
    at Array.map (<anonymous>)
```

With the last one, it was a 404.

Thanks!

**Comment by bnielsen1965** [comment]
I believe the problem is that you cannot use the ws module in webpack...

https://github.com/websockets/ws/issues/1117#issuecomment-302865063

Browsers already have a built in keep alive method for websockets so I didn't even consider the possibility of running wska in a browser.

That said, based on that issue comment in the ws project it looks like it should be possible with some additional code so that wska would use the browsers websocket in place of the ws module.

I'll have to look further, if I recall the events work a little bit different in the browsers so it may need some code changes in that part of wska as well.

**Comment by bnielsen1965** [comment]
Couple of questions for you...

What did you need to import in webpack to get it to accept the ws module? I'm getting some warnings for missing packages.


And do you know if there is a way to tell webpack to not process a require in an imported module? Since the browser already has Websocket we don't actually need the ws module.

**Comment by bnielsen1965** [comment]
One last note. It looks like the recommended solution is to add a shim for webpack that will replace ws with the browser's Websocket. One suggest shim is here...

https://github.com/SocketCluster/socketcluster-client/blob/master/lib/ws-browser.js

I've never used webpack before so it will take awhile to figure this out. But I think it may still require some changes to wska due to the differences between ws and the browser's Websocket methods.

**Comment by kittaakos** [comment]
> I believe the problem is that you cannot use the ws module in webpack...

Exactly, that's why I was asking whether it is possible at all. I have seen the [`ws` dependency](https://github.com/bnielsen1965/wska/blob/master/index.js#L11) in the code.

> What did you need to import in webpack to get it to accept the ws module?

Eventually, we had the problem with `crypto`. We had to shim it from webpack; then we ran into [another problem](https://github.com/theia-ide/theia/issues/1410#issuecomment-370021288).

> And do you know if there is a way to tell webpack to not process a require in an imported module?

We tried to follow [this](https://mixmax.com/blog/requiring-node-builtins-with-webpack) approach, without changing the source.

Our initial idea was to replace our [pladaria/reconnecting-websocket](https://github.com/pladaria/reconnecting-websocket) dependency with wska. But finally, we dropped that idea.

Thank you for your time! +1 for closing this issue.

**Comment by bnielsen1965** [comment]
I had some time to look at this further and I found that it is currently impossible to use wska in a browser because the browser developers chose to not expose the WebSocket ping() method and there is no way to set the opcode for a Websocket frame to the ping opcode.

The long story, I was able to create a webpack shim for ws that would allow me to run wska in the browser but when it came time to implement the ws ping/pong methods in the shim that enable a heartbeat I ran into the browser WebSocket issue.

I also found that the web browsers do respond to ping frames with a pong frame per the specification. So you can add a ws.ping() to your server code to keep the socket connection alive. But that doesn't help much if the client side loses the connection and is not aware.

It is very annoying but you will need to use a keep alive method on the client side that doesn't rely on the ping/pong frames defined in RFC6455. Sorry I couldn't help.
